database:
  dialect: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: wdh961100
  dbname: zhlg
  charset: utf8mb4
  parse_time: true
  loc: Local
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: true 